[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["./node_modules/.bin/ng build --configuration production"]

[start]
cmd = "static-server dist/tiferet-david-app"
